### ISSUE TITLE
地平线5冻结了之后还是有个全屏黑屏框请问怎么解决

### ISSUE THREAD

**Issue by occerseimj** [superDMS/HsFreezer-Hidden-in-the-snow-#1]
使用这个软件将地平线5冻结后，电脑还是黑屏，按win+d可以退出到桌面但是点任意软件黑屏随之弹出

**Comment by superDMS** [comment]
请勿使用的是哪个版本?可以用最新版试试?

**Comment by superDMS** [comment]
请问使用的是哪个版本?请用最新v1.21版本试试

**Comment by superDMS** [comment]
请问使用的是哪个版本?请用最新v1.21版本试试?  还有请检查选择的程序映像名是否是主进程映像,如果这些细节都排除了, 请等我适配.

**Comment by superDMS** [comment]
请问使用的是哪个版本?这个情况是100%复现还是偶发? 请用最新v1.21版本试试, 还有请检查选择的程序映像名是否是主进程映像,如果这些细节都排除了, 请等我适配.
