### ISSUE TITLE
[BUG]原神游戏主界面按钮无法点击

### ISSUE THREAD

**Issue by kqtic** [superDMS/HsFreezer-Hidden-in-the-snow-#11]
版本：V1.41
描述：使用hsfreezer冻结游戏并解冻之后，原神主界面上方按钮无法点击。关闭hsfreezer重启游戏后恢复正常。

无法点击的按钮如下图红框所示：
![image](https://github.com/superDMS/HsFreezer-Hidden-in-the-snow-/assets/62581288/8d5fb180-08f9-4989-8170-317223d46056)

**Comment by superDMS** [comment]
可以尝试用仅最小化模式   试试    .也可以等待后续排查

**Comment by kqtic** [comment]
经过排查，原因在于妙控拖拽，妙控拖拽使用的alt键与原神冲突，关掉这个功能就没问题了。

**Comment by superDMS** [comment]
对 是的! 上去玩了一下..刚想说...
