### ISSUE TITLE
开源问题

### ISSUE THREAD

**Issue by CeitherNSW** [superDMS/HsFreezer-Hidden-in-the-snow-#12]
作者是否考虑后续开源

**Comment by superDMS** [comment]
后续我整理后会在社区发布一些相关的实现代码.敬请期待

**Comment by Luluno01** [comment]
有考虑写一篇文章解释一下基本原理、技术挑战和解决方案，或者发表软工论文吗？太好奇了QAQ

**Comment by superDMS** [comment]
已经分享部分源码.请自行调试使用.

**Comment by Luluno01** [comment]
> 已经分享部分源码.请自行调试使用.

`main` branch里还是只有一个README？请问是要到其它社区看吗？
