### ISSUE TITLE
妙控拖曳问题

### ISSUE THREAD

**Issue by 0urlife** [superDMS/HsFreezer-Hidden-in-the-snow-#14]
开启雪藏使用alt+tab会导致鼠标左键无法选择窗口，只能移动整个缩略窗口移动，鼠标中键也无法使用来删除窗口，

**Comment by superDMS** [comment]
收到! alt+tab暂且可用右键来选择 ! 等后续待对此修复

**Comment by superDMS** [comment]
已经修复这个问题.
