### ISSUE TITLE
为什么github上不直接放最新版本呢

### ISSUE THREAD

**Issue by cero-ss** [superDMS/HsFreezer-Hidden-in-the-snow-#16]
既然软件更新提示到github上，为什么不直接在github上更新呢，放了2个网盘链接还要额外注册，结果现在网盘里也没有还要去qq群，这不是增加时间成本了吗

**Comment by shengsuoOVO** [comment]
为了引流呗，把用户都引到QQ群，到时候是打广告也好，干点什么商业活动也好都方便

**Comment by PaiOVO** [comment]
> 既然软件更新提示到github上，为什么不直接在github上更新呢，放了2个网盘链接还要额外注册，结果现在网盘里也没有还要去qq群，这不是增加时间成本了吗

为了引流呗，把用户都引到QQ群，到时候是打广告也好，干点什么商业活动也好都方便

**Comment by superDMS** [comment]
更新太频繁   github上传特别费劲    扔Q群方便得多   网盘是因为本月限流     老用户都知道之前都是几个渠道一起更新的.
