### ISSUE TITLE
使用hsfreezer之后，导致v2rayn经常闪退

### ISSUE THREAD

**Issue by Z46I4W5476SJA** [superDMS/HsFreezer-Hidden-in-the-snow-#18]
![image](https://github.com/superDMS/HsFreezer-Hidden-in-the-snow-/assets/45085951/bc3aae2b-0e85-485c-8188-7804f591fee2)
如图  当前仅冻结了两个进程   但是每次打开v2rayn   软件启动后    一般在一分钟内 就会闪退了   使用hsfreezer之前   没有存在这种问题   还希望作者看看能否解决  实在不好解决 我就关了这个issue

**Comment by superDMS** [comment]
希望可以录个屏  , 通过qq发给我...我光听这个描述实在没法思考出他们有啥纠缠的关系......非常的奇怪......好端端的咋影响到没冻结的进程呢?(如果是冻结你说的那个软件导致闪退还有点线索)...

**Comment by Z46I4W5476SJA** [comment]
> 希望可以录个屏 , 通过qq发给我...我光听这个描述实在没法思考出他们有啥纠缠的关系......非常的奇怪......好端端的咋影响到没冻结的进程呢?(如果是冻结你说的那个软件导致闪退还有点线索)...



> 希望可以录个屏 , 通过qq发给我...我光听这个描述实在没法思考出他们有啥纠缠的关系......非常的奇怪......好端端的咋影响到没冻结的进程呢?(如果是冻结你说的那个软件导致闪退还有点线索)...

emmmm  我也觉得挺玄学的    但是录屏估计也解决不了    感觉可能需要看v2rayn的崩溃日志才能知道为啥     我先关了吧    如果后面还有人也发现这个问题   再去看看是啥原因    目前软件已经挺好用的了  感谢给我们带来这款软件

**Comment by silentway01** [comment]
我也是这样，把hsfreezer删除了还是会经常闪退，有解决方案吗？
