### ISSUE TITLE
使用 Lily 快捷启动工具时，若开启设置中 动作-停靠屏幕边缘时吸附 功能，在 HsFreezer 冻结后会阻塞鼠标/键盘

### ISSUE THREAD

**Issue by edwinaze** [superDMS/HsFreezer-Hidden-in-the-snow-#19]
问题设置：
![图片](https://github.com/superDMS/HsFreezer-Hidden-in-the-snow-/assets/53467361/9159b05e-55ca-43e3-8466-4061495cd8dd)

勾选后再冻结就会导致鼠标移动极其卡顿，完全无法正常使用，键盘输入同样有严重阻塞，当切换窗口聚焦到 HsFreezer 便恢复。Lily 在我不开高能耗软件时候居然常驻 TOP1 能耗，难绷。
![图片](https://github.com/superDMS/HsFreezer-Hidden-in-the-snow-/assets/53467361/5d758cb7-a22f-4567-b6b8-060ae16956e6)

很奇怪的bug，在这里提一下免得有人遇到同样的情况不知道怎么回事。

**Comment by superDMS** [comment]
建议处理方式: 在雪藏拉黑拉黑lily   因为他属于某些光标监控类软件, 冻结他会阻塞他对鼠标的构造 导致这个状况. 这个功耗仅是相对量  在没运行大型游戏之前  可以忽略其排名.
