### ISSUE TITLE
冻结英雄联盟之后，电脑睡眠，第二天唤醒电脑，查看雪藏，冻结的英雄联盟进程一开始还有  然后过几秒后就没了

### ISSUE THREAD

**Issue by Z46I4W5476SJA** [superDMS/HsFreezer-Hidden-in-the-snow-#20]
冻结的进程是leagueclientux.exe
唤醒电脑后，一定要把鼠标点击一下雪藏   然后看一下冻结的列表  发现英雄联盟这个进程就没了

**Comment by superDMS** [comment]
leagueclientux.exe这个进程  据我测试不用冻结,  他在后台基本0消耗 ,  由于他是需要网络交互类的进程  可能是长时间冻结离线会导致他与服务器对不上时间导致崩溃 .  可再自行测试一下他的崩溃机制  也有可能是其他缘故导致

**Comment by Z46I4W5476SJA** [comment]
> leagueclientux.exe这个进程 据我测试不用冻结, 他在后台基本0消耗 , 由于他是需要网络交互类的进程 可能是长时间冻结离线会导致他与服务器对不上时间导致崩溃 . 可再自行测试一下他的崩溃机制 也有可能是其他缘故导致

测试了一下   睡眠之后   不冻结  有时候英雄联盟也崩溃了     垃圾马服
