### ISSUE TITLE
关于网盘

### ISSUE THREAD

**Issue by ZeronoFreya** [superDMS/HsFreezer-Hidden-in-the-snow-#21]
感谢作者的贡献，非常好的软件！
有个疑问，是关于网盘的，如果夸克能给您带来收益，直接关闭本话题就行。
否则，为什么不选择更好的呢？目前包大小超过了100M，蓝奏云可能不太行了，123盘也不错，谷歌或者mega有一定使用门槛……
主要是夸克必须要安装客户端才能下载，速度也没比百度更好，我现在是为了这款软件专门注册的夸克……

**Comment by superDMS** [comment]
你能访问github,可以直接在github的release里下载呀:https://github.com/superDMS/HsFreezer-Hidden-in-the-snow-/releases/ 
   或者qq群, 我放置了挺多渠道, 夸克仅是其中一个.

**Comment by ZeronoFreya** [comment]
感谢，我之前看的时候还没有链接。我出于个人原因不用tx的软件与游戏……虽然有些游戏使用了tx的反作弊，比如尘白，真想给删了，强迫症了
