### ISSUE TITLE
【一些优化的建议】能否增加对win10默认服务的效果说明，特别是冻结后的影响

### ISSUE THREAD

**Issue by jkqxl** [superDMS/HsFreezer-Hidden-in-the-snow-#22]
不清楚是冻结了哪个服务，导致不论是进行任何操作都具卡无比。

普通模式：白名单应该独立出来一个界面，并且从所有的隐藏，因为很多时候都不清楚是不是已经加入了白名单
快照模式：白名单还需要自己输入程序名称，而不是与普通模式的白名单一样

**Comment by superDMS** [comment]
第一个服务问题, 这个服务有太多的未知情况,且每台机子的软件不一样服务也不太一样,不太好做说明,建议不要去冻结服务进程.(可自行测试)
普通模式和快照模式的建议很好, 后续版本会陆续采纳修改 谢谢!

**Comment by jkqxl** [comment]
> 第一个服务问题, 这个服务有太多的未知情况,且每台机子的软件不一样服务也不太一样,不太好做说明,建议不要去冻结服务进程.(可自行测试) 普通模式和快照模式的建议很好, 后续版本会陆续采纳修改 谢谢!

@superDMS 

能否依据 以下内容 给予相应的说明，现在每个服务还是需要单独在网上查询，再确认是否要冻结，也是很麻烦的事情
https://learn.microsoft.com/zh-cn/windows/iot/iot-enterprise/optimize/services

目前来说，感觉使用上依然不是特别的方便，而大部分人真正需要的其实也就是类似 memory 的一个进程、内存的清理功能（在保留需要的软件不关闭的情况下），只不过同类软件并不像作者软件的效果更好，虽然更加方便。
https://github.com/H3d9/memory_cleaner
