### ISSUE TITLE
程序卸载问题

### ISSUE THREAD

**Issue by abc43992899** [superDMS/HsFreezer-Hidden-in-the-snow-#23]
请问删除程序文件夹后C盘里面的Microsoft\Components文件夹会自动删除吗，还是需要手动删除？
更新到最新版本这个文件夹貌似也没有文件更新，是否可以删除呢

**Comment by superDMS** [comment]
这个是核心守护进程进程的必要环境,如果最终需要卸载可以手动完全删除(或者等系统自行清理共享文件), 如果还在继续使用不要删除这个文件夹.
