### ISSUE TITLE
软件升级包问题

### ISSUE THREAD

**Issue by bingsunny0730** [superDMS/HsFreezer-Hidden-in-the-snow-#25]
能不能增加一种单独文件夹替换的升级压缩包形式？见过其它py打包的项目后续升级也是采用这种方式，毕竟替换的都是些数据文件，对于之前已经安装过的也没必要重复下载大exe包吧，至少可以解决某些安装问题以及省时省空间。
还有能否将更新提示默认改为不勾选状态？有时旧版本用得好好的又不想更新，突然来个弹窗，感觉挺影响体验的。

**Comment by superDMS** [comment]
更新勾选框是有保留状态的, 对于升级包,会在日后考虑做成单独覆盖的形式,感谢建议.
