### ISSUE TITLE
冻结软件 没有解冻  直接关机了  现在软件无法使用

### ISSUE THREAD

**Issue by qu270051387** [superDMS/HsFreezer-Hidden-in-the-snow-#28]
系统：win10 ltsc 1809
程序：spotube.exe          https://github.com/KRTirtho/spotube
触发条件：使用雪藏冻结spotube后，没有解冻，直接关机
问题：重新打开电脑后无法正常运行spotube，第一次双击spotube后可以看到进程中出现了spotube.exe但是没有窗口弹出，再次双击spotube窗口体现，但是整个窗口是空白的，无法正常显示。
![image](https://github.com/user-attachments/assets/ea97a744-4e77-464e-82c4-6a926e7ceb81)

![image](https://github.com/user-attachments/assets/299a9d33-2e6d-4879-96a3-0426d810efef)

**Comment by qu270051387** [comment]
并且点击右上角的×并不能关闭程序   需要在任务管理器里结束进程才能消失

**Comment by superDMS** [comment]
雪藏冻结功能与软件下次能否正常启动无必然相关联系, 可尝试重装出现异常的软件.
