### ISSUE TITLE
NT版QQ无法冻结

### ISSUE THREAD

**Issue by shuixxing233** [superDMS/HsFreezer-Hidden-in-the-snow-#29]
![image](https://github.com/user-attachments/assets/979b63c2-336b-4f01-81ba-84ca431649ba)
亲测选择QQ后后台占用内存还是正常的大，只是会比没有选择是小个十几MB

**Comment by superDMS** [comment]
这个冻结是冻结CPU 和GPU  不是让内存变小哦!
