### ISSUE TITLE
大力支持 作者牛X : windows状态栏没有图标显示 如图第一个是雪藏

### ISSUE THREAD

**Issue by zhihui1999** [superDMS/HsFreezer-Hidden-in-the-snow-#3]
![image](https://github.com/superDMS/HsFreezer-Hidden-in-the-snow-/assets/36041260/5cd1846d-8c4e-474c-949a-dc080405b592)

**Comment by zhihui1999** [comment]
win11 最新版

**Comment by superDMS** [comment]
好的, 外观问题粗心了,过后补上!

**Comment by superDMS** [comment]
已解决
