### ISSUE TITLE
一些使用上的体验建议

### ISSUE THREAD

**Issue by ZeronoFreya** [superDMS/HsFreezer-Hidden-in-the-snow-#31]
不用qq之类的，就发在这吧。

* 打开进阶面板后窗体会自动移动到主屏，我是双屏。
* 自呼吸某些游戏(比如鸣潮)，在呼吸的时候会发出游戏内声音，且会强制把鼠标移动到屏幕中心

其他都挺好的，不知道能不能优化一下。
最后，感谢作者的贡献！

**Comment by superDMS** [comment]
嗯 双屏这个情况已记录,  今后会适配~~感谢反馈
关于呼吸发出声音是正常现象 因为(呼吸就是解冻状态)   对于强制把鼠标移到中间, 是快捷键弹出提示窗口导致的附着吧?

**Comment by ZeronoFreya** [comment]
> 嗯 双屏这个情况已记录, 今后会适配~~感谢反馈 关于呼吸发出声音是正常现象 因为(呼吸就是解冻状态) 对于强制把鼠标移到中间, 是快捷键弹出提示窗口导致的附着吧?

声音这个，或许给这个程序单独静音就可以，至少win11支持。
鼠标问题，应该是游戏对鼠标做了什么限制，比如动作游戏会把鼠标控制在窗口范围之内，防止按键丢失？
这个可能不好优化，但当需要鼠标做别的事情的时候(比如绘画､建模)，刷的一下鼠标移到中心……或许网游就该直接关掉

**Comment by superDMS** [comment]
> > 嗯 双屏这个情况已记录, 今后会适配~~感谢反馈 关于呼吸发出声音是正常现象 因为(呼吸就是解冻状态) 对于强制把鼠标移到中间, 是快捷键弹出提示窗口导致的附着吧?
> 
> 声音这个，或许给这个程序单独静音就可以，至少win11支持。 鼠标问题，应该是游戏对鼠标做了什么限制，比如动作游戏会把鼠标控制在窗口范围之内，防止按键丢失？ 这个可能不好优化，但当需要鼠标做别的事情的时候(比如绘画､建模)，刷的一下鼠标移到中心……或许网游就该直接关掉

好的  感谢反馈!
