### ISSUE TITLE
其他用途

### ISSUE THREAD

**Issue by CNenfan** [superDMS/HsFreezer-Hidden-in-the-snow-#32]
请问一下作者，软件能否针对其他软件进行优化呢，平时办公软件需要多开比如PS PR AE Unity这种还是没什么问题，但是打开微信这种蛋疼软件电脑性能羸弱就受不了

**Comment by superDMS** [comment]
> 请问一下作者，软件能否针对其他软件进行优化呢，平时办公软件需要多开比如PS PR AE Unity这种还是没什么问题，但是打开微信这种蛋疼软件电脑性能羸弱就受不了

可以的呀, 雪藏可以冻结很多非游戏进程, 不光能用来打游戏的,~ 冻结在各种进程之间都适用`
