### ISSUE TITLE
战地2042好像冻不了

### ISSUE THREAD

**Issue by Alpha-Qian** [superDMS/HsFreezer-Hidden-in-the-snow-#36]
<img width="1280" alt="屏幕截图 2024-09-21 095317" src="https://github.com/user-attachments/assets/39cf2fd7-006d-4fe5-b5a9-db1f9c62a061">

**Comment by Alpha-Qian** [comment]
实测战地5也不管用，cpu占用没变化
<img width="644" alt="屏幕截图 2024-09-22 204305" src="https://github.com/user-attachments/assets/3b4cf186-cf92-446b-9ba8-90135b531d29">

**Comment by superDMS** [comment]
2024有一定反调试对抗 这个暂时误解
