### ISSUE TITLE
V1.28 Windows 11 无法启动

### ISSUE THREAD

**Issue by lleohao** [superDMS/HsFreezer-Hidden-in-the-snow-#5]
**系统信息如下**

处理器	AMD Ryzen 5 3600X 6-Core Processor                4.10 GHz
机带 RAM	32.0 GB
系统类型	64 位操作系统, 基于 x64 的处理器
笔和触控	没有可用于此显示器的笔或触控输入

版本	Windows 11 专业版
版本	23H2
安装日期	‎2022/‎9/‎21
操作系统版本	22631.3447
体验	Windows Feature Experience Pack 1000.22688.1000.0

**Comment by superDMS** [comment]
诶?  不应该呀   请看看是否受到权限拦截等      (也许是7zip自解压问题, 您下载一个解压软件, 右键对安装包进行解压试试)

**Comment by zhoufxiang** [comment]
> 诶? 不应该呀 请看看是否受到权限拦截等 (也许是7zip自解压问题, 您下载一个解压软件, 右键对安装包进行解压试试)

我也是win11无法启动，cpu 锐龙7745hx，版本是最新的1
31

**Comment by zhoufxiang** [comment]
> 诶? 不应该呀 请看看是否受到权限拦截等 (也许是7zip自解压问题, 您下载一个解压软件, 右键对安装包进行解压试试)
直接双击快捷方式是进入了我的notepad++页面了，右键快捷方式也无法运行
Set UZC = CreateObject("Shell.Application") 
UZC.ShellExecute "E:\雪藏HsFreezer\data\Sys\Cert\setup.bat", "", "", "runas", 1

**Comment by lleohao** [comment]
我的问题，那个 exe 原来是个解压包，我一直运行那个 exe
