### ISSUE TITLE
[Feature]增加关联冻结功能

### ISSUE THREAD

**Issue by youlan2333** [superDMS/HsFreezer-Hidden-in-the-snow-#8]
有些程序单独冻结某一进程没有效果，如mumu模拟器需同时冻结MuMuPlayer.exe和MuMuVMMHeadless.exe，可否考虑增加关联冻结功能？

**Comment by superDMS** [comment]
由于有太多软件, 软件间的各种进程关系不尽相同  , 这类很难全局适配(当然,我会一直跟进,如果有好的方案会第一时间放出)
